### ISSUE TITLE
Class 'Symfony\Component\HttpClient\HttpClient' not found on non-composer installation

### ISSUE THREAD

**Issue by fdeussen** [maikschneider/bw_cache_uri#1]
If bw_cache_uri is installed directly via Extension-Manager (non-composer) symfonys httpclient is missing and external resources can't be loaded.

**Comment by maikschneider** [comment]
Hey @fdeussen,
thanks for the feedback! I just released version [version 1.1.4](https://github.com/maikschneider/bw_cache_uri/releases/tag/v1.1.4) where I shipped the dependencies. Could you please test?

**Comment by fdeussen** [comment]
Hi @maikschneider,
Thanks a lot! Now in a non-composer-installation the external source gets loaded.

But if I try to rebuild the examples from readme and use the filtering option the next somfony module is marked as missing:

"To filter with a CSS selector, install the CssSelector component ("composer require symfony/css-selector"). Or use filterXpath instead."

**Comment by maikschneider** [comment]
Ah, great. Okay, I just removed the css-selector dependency because I could not find any occurrence of it in the code. 

Sry, I have no non-composer installation at the moment. Now I re-added it and included it in [version 1.1.5](https://github.com/maikschneider/bw_cache_uri/releases/tag/v1.1.5). Does it work?

**Comment by fdeussen** [comment]
Load HTML/XML: works
Filter (CSS selectors): works
Sheduler Task: works
:-))
next will test Post Processors

Thanks a lot! Is somewhere a kind of wishlist, 'buy me a beer', some else donate or billing option?

**Comment by maikschneider** [comment]
Cool, I'm glad to hear that! Thank you, I'm happy if you like my work and report bugs :)
