### ISSUE TITLE
Problem with typo3 11.5 and news Extension after installing bw_cache_uri

### ISSUE THREAD

**Issue by toancao91** [maikschneider/bw_cache_uri#4]
When a News element is present on the page and displays the List View, I encounter the following error:

`'The default controller for extension "News" and plugin "Pi1" cannot be determined. Please check for TYPO3\CMS\Extbase\Utility\ExtensionUtility::configurePlugin() in your ext_localconf.php.`

The Problem is that, how the dom_processor options is added to the tt_content tca. The provided code should be placed in the tt_content.php instead ext_tables.php, after the definition of the 'parsing_options' palette.

```
// A4. Show palette
$GLOBALS['TCA']['tt_content']['palettes']['parsing_options'] = [
    'showitem' => 'dom_uri,--linebreak--,dom_filter,--linebreak--,dom_processor'
];

// B - Read TypoScript and add DOM processors
$objectManager = GeneralUtility::makeInstance(ObjectManager::class);
$configurationManager = $objectManager->get(ConfigurationManager::class);
$typoscript = $configurationManager->getConfiguration(ConfigurationManagerInterface::CONFIGURATION_TYPE_FULL_TYPOSCRIPT);

if (isset($typoscript['plugin.']['tx_bwcacheuri.'])) {
    foreach ($typoscript['plugin.']['tx_bwcacheuri.']['settings.']['postProcessors.'] as $class => $postProcessor) {
        $GLOBALS['TCA']['tt_content']['columns']['dom_processor']['config']['items'][] = [
            $postProcessor['label'],
            substr($class, 0, -1)
        ];
    }
}
```

Version:
TYPO3 11.5.3

bw_cache_uri 1.1.3

news 10.0.3

**Comment by maikschneider** [comment]
Hey @toancao91, thanks for reporting! I justed published [v1.1.6](https://github.com/maikschneider/bw_cache_uri/releases/tag/v1.1.6) which should resolve the issue.
